안의 글을 모두에게 바칩니다. 데이터 타입 정리~🚀
woowacourse-study/2022-javascript-deepdive pull request #4
Opened 2022-04-04 13:05 UTC by jin7969

2022-04-05 04:15 UTC, jswith reviewed
'안' 녕하세요.
미션 때문에 바쁘실텐데도 불구하고
기한 준수해서 작성해주신 점 멋있습니다! 👍
정리해주신 내용 잘 확인하였고 궁금한 내용 코멘트 남겨드렸으니 편하게 답변해주세요! 💬

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +- 참조형 : 주솟값들로 이루어진 묶음을 가리키는 주솟값을 복제
참조형 데이터에는 어떤 것들이 있나요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +- 기본형 : 주솟값을 바로 복제
기본형 데이터에는 어떤 것들이 있나요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +  - 메모리를 더욱 효율적으로 관리하기 위해
도대체 어떤 방식으로 관리하길래 메모리를 더욱 효율적으로 관리할 수 있는건가요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +- 참조형 데이터에서 객체 자체를 변경 -> 불변
객체 자체를 변경한다는게 어떤 의미죠?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +- 값으로 전달받은 객체를 변경 하더라도 원본 객체가 변하지 않아야 하는 경우 필요하다
원본 객체가 변하지 않아야하는 사례가 뭐가 있을까요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +원시 타입은 깊은 복사가 된다. 객체에서는 Object.assign(), 전개 연산자(Spread Operator), JSON 객체 메서드 와 같은 방법이 있다.
Object.assign()을 사용하면 깊은 복사가 완벽하게 될까요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +- 아무것도 참조하고 있지 않다라는 의미가 담겨 있다
명시적으로 null을 지정하는 사례로는 뭐가 있을까요?

2022-04-05 04:15 UTC, jswith commented on 안/01-데이터-타입.md
> +얕은 복사 때문에, 사본의 데이터를 변경하더라도, 원본의 데이터도 변경된다.
얕은 복사 시 원본과 사본의 데이터가 같이 바뀌는건 어떤 점 때문인가요? 주솟값만 복사한다? 좀 더 상세하게 설명해주실 수 있나요?

2022-04-05 05:07 UTC, jswith requested changes
test

2022-04-07 04:37 UTC, LAH1203 reviewed
안녕하세요 안! 정리해주신거 잘 봤습니다 😁 너무 깔끔하게 잘 해주셨던데요? 👍🏻👍🏻
읽다가 궁금한 점 몇 개 질문 남겼는데, 편하실 때 답변 해주시면 될 것 같아요~ 안 화이팅! :)

2022-04-07 04:37 UTC, LAH1203 commented on 안/01-데이터-타입.md
> +- 차이점 : `undefined`는 변수를 선언만 하더라도 할당되지만 `null`은 변수를 선언한 후에 null로 값을 바꾼다
이거 외에도 undefined와 null의 차이점이 또 있을까요?

2022-04-08 10:53 UTC, jin7969 commented on 안/01-데이터-타입.md
> +- 참조형 : 주솟값들로 이루어진 묶음을 가리키는 주솟값을 복제
object, array, function, date, regExp(정규 표현식) 등이 있어요!

2022-04-08 10:55 UTC, jin7969 commented on 안/01-데이터-타입.md
> +- 기본형 : 주솟값을 바로 복제
number, string, boolean, null, undefined, symbol 등이 있어요

2022-04-10 08:54 UTC, jswith approved these changes

2022-04-10 10:24 UTC, moonheekim0118 approved these changes
안녕하세요 안 ~~ 정리해주신것 잘봤습니다 :D 정리하느라 수고하셨어요!

2022-04-11 05:15 UTC, jin7969 commented on 안/01-데이터-타입.md
> +- 내부의 모든 값들을 하나하나 찾아서 전부 복사하는 방법
실제 값을 복사한다고 알고 있습니다.
혹시 다른 의미가 있나요??

2022-04-11 05:24 UTC, jin7969 commented on 안/01-데이터-타입.md
> +- 차이점 : `undefined`는 변수를 선언만 하더라도 할당되지만 `null`은 변수를 선언한 후에 null로 값을 바꾼다
- undefined은 변수를 선언하고 값을 할당하지 않은 상태, null은 변수를 선언하고 빈 값을 할당한 상태(빈 객체) 입니다.
- undefined 변수의 초기 값은 undefined 원시 값이고,
null은 어떤 값이 의도적으로 비어있음을 표현합니다.

2022-04-11 05:25 UTC, jin7969 commented on 안/01-데이터-타입.md
> +  - 데이터 변환을 자유롭게 할 수 있다
저는 그렇게 이해했어요!

2022-04-11 06:56 UTC, LAH1203 commented on 안/01-데이터-타입.md
> +- 내부의 모든 값들을 하나하나 찾아서 전부 복사하는 방법
오 아뇨! 그냥 이해하신바가 저랑 어떻게 다를지가 궁금했어요 :)

2022-04-11 06:56 UTC, LAH1203 approved these changes
'안' 수고하셨습니다~! 굿굿 🥳

2022-04-11 13:38 UTC, merged